/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 10:22:23 GMT 2019
 */

package eu.supersede.integration.api.security;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.security.IFAuthenticationManager;

public class IFAuthenticationManager_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IFAuthenticationManager iFAuthenticationManager0 = null;
        iFAuthenticationManager0 = new IFAuthenticationManager();
  }
}
