/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:55:55 GMT 2019
 */

package eu.supersede.integration.api.feedback.repository.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.orchestrator.types.Mechanism;
import eu.supersede.integration.api.feedback.repository.types.Feedback;
import eu.supersede.integration.api.feedback.repository.types.RatingFeedback;

public class RatingFeedback_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      long long0 = ratingFeedback0.getMechanismId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = ratingFeedback0.getMechanism();
      assertNull(mechanism0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setRating((-5695));
      assertEquals((-5695), ratingFeedback0.getRating());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      String string0 = ratingFeedback0.toString();
      assertEquals("RatingFeedback[id=0]", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      long long0 = ratingFeedback0.getId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = new Mechanism();
      ratingFeedback0.setMechanism(mechanism0);
      mechanism0.setId(2085L);
      Mechanism mechanism1 = ratingFeedback0.getMechanism();
      assertSame(mechanism1, mechanism0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Feedback feedback0 = ratingFeedback0.getFeedback();
      assertNull(feedback0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Feedback feedback0 = new Feedback("/\bE'Vg", "RatingFeedback[id=%d]", (-1971L), 686L, "/\bE'Vg");
      RatingFeedback ratingFeedback0 = new RatingFeedback(feedback0, "/\bE'Vg", (-1202), 725L);
      int int0 = ratingFeedback0.getRating();
      assertEquals(725L, ratingFeedback0.getMechanismId());
      assertEquals((-1202), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      String string0 = ratingFeedback0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setTitle("=g]{|ctF@o&+1E");
      String string0 = ratingFeedback0.getTitle();
      assertEquals("=g]{|ctF@o&+1E", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Feedback feedback0 = new Feedback("", "", 0L, 0L, "");
      ratingFeedback0.setFeedback(feedback0);
      Feedback feedback1 = ratingFeedback0.getFeedback();
      assertEquals("", feedback1.getTitle());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Feedback feedback0 = new Feedback("/\bE'Vg", "RatingFeedback[id=%d]", (-1971L), 686L, "/\bE'Vg");
      RatingFeedback ratingFeedback0 = new RatingFeedback(feedback0, "/\bE'Vg", (-1202), 725L);
      ratingFeedback0.getFeedback();
      assertEquals(725L, ratingFeedback0.getMechanismId());
      assertEquals((-1202), ratingFeedback0.getRating());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Feedback feedback0 = new Feedback("m (`E'", "m (`E'", (-233L), (-1482L), "m (`E'");
      feedback0.setId((-233L));
      RatingFeedback ratingFeedback0 = new RatingFeedback(feedback0, "S[)bGOH%z$I", (-1786), 2147483647L);
      ratingFeedback0.getFeedback();
      assertEquals(2147483647L, ratingFeedback0.getMechanismId());
      assertEquals((-1786), ratingFeedback0.getRating());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Feedback feedback0 = new Feedback("!=+:", "!=+:", 1153L, (-266L), "ATTACHMENT_TYPE");
      feedback0.setId(1153L);
      RatingFeedback ratingFeedback0 = new RatingFeedback(feedback0, "", 729, (-266L));
      ratingFeedback0.getFeedback();
      assertEquals(729, ratingFeedback0.getRating());
      assertEquals((-266L), ratingFeedback0.getMechanismId());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setId((-2147483648L));
      long long0 = ratingFeedback0.getId();
      assertEquals((-2147483648L), long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setId(1482L);
      long long0 = ratingFeedback0.getId();
      assertEquals(1482L, long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = new Mechanism();
      mechanism0.setId((-5695));
      ratingFeedback0.setMechanism(mechanism0);
      Mechanism mechanism1 = ratingFeedback0.getMechanism();
      assertEquals((-5695L), mechanism1.getId());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = new Mechanism();
      mechanism0.setOrder((-5695));
      ratingFeedback0.setMechanism(mechanism0);
      Mechanism mechanism1 = ratingFeedback0.getMechanism();
      assertFalse(mechanism1.isActive());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = new Mechanism();
      mechanism0.setOrder(1);
      ratingFeedback0.setMechanism(mechanism0);
      Mechanism mechanism1 = ratingFeedback0.getMechanism();
      assertEquals(0L, mechanism1.getId());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      Mechanism mechanism0 = new Mechanism();
      ratingFeedback0.setMechanism(mechanism0);
      mechanism0.setActive(true);
      Mechanism mechanism1 = ratingFeedback0.getMechanism();
      assertEquals(0, mechanism1.getOrder());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback((Feedback) null, "", 0, (-1242L));
      long long0 = ratingFeedback0.getMechanismId();
      assertEquals(0, ratingFeedback0.getRating());
      assertEquals((-1242L), long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setMechanismId(2085L);
      long long0 = ratingFeedback0.getMechanismId();
      assertEquals(2085L, long0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Feedback feedback0 = new Feedback((String) null, "B+~If4Z?__MEcy", 0L, 435L, "S-oy[3O[R.");
      RatingFeedback ratingFeedback0 = new RatingFeedback(feedback0, (String) null, 1976, 0L);
      int int0 = ratingFeedback0.getRating();
      assertEquals(1976, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      int int0 = ratingFeedback0.getRating();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      RatingFeedback ratingFeedback0 = new RatingFeedback();
      ratingFeedback0.setTitle("");
      String string0 = ratingFeedback0.getTitle();
      assertEquals("", string0);
  }
}
