/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:57:33 GMT 2019
 */

package eu.supersede.integration.api.feedback.repository.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.repository.types.StatusOption;

public class StatusOption_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      Integer integer0 = statusOption0.getId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      int int0 = statusOption0.getOrder();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      boolean boolean0 = statusOption0.isUserSpecific();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      String string0 = statusOption0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      Integer integer0 = new Integer((-2880));
      statusOption0.setId(integer0);
      Integer integer1 = statusOption0.getId();
      assertEquals((-2880), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      Integer integer0 = Integer.getInteger("|_r", 2911);
      statusOption0.setId(integer0);
      Integer integer1 = statusOption0.getId();
      assertEquals(2911, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      Integer integer0 = new Integer(0);
      statusOption0.setId(integer0);
      Integer integer1 = statusOption0.getId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      statusOption0.setName("");
      String string0 = statusOption0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      statusOption0.setName("eu.supersede.integration.api.feedback.repository.types.StatusOption");
      String string0 = statusOption0.getName();
      assertEquals("eu.supersede.integration.api.feedback.repository.types.StatusOption", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      statusOption0.setOrder((-796));
      int int0 = statusOption0.getOrder();
      assertEquals((-796), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      statusOption0.setOrder(117);
      int int0 = statusOption0.getOrder();
      assertEquals(117, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StatusOption statusOption0 = new StatusOption();
      statusOption0.setUserSpecific(true);
      boolean boolean0 = statusOption0.isUserSpecific();
      assertTrue(boolean0);
  }
}
