/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 09:53:52 GMT 2019
 */

package eu.supersede.integration.api.adaptation.dashboad.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.adaptation.dashboad.types.Adaptation;
import eu.supersede.integration.api.adaptation.dashboad.types.Enactment;
import java.util.Date;
import org.evosuite.runtime.mock.java.util.MockDate;

public class Enactment_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Adaptation adaptation0 = enactment0.getAdaptation();
      assertNull(adaptation0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Date date0 = enactment0.getEnactment_completion_time();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      boolean boolean0 = enactment0.isResult();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      enactment0.setResult(true);
      boolean boolean0 = enactment0.isResult();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Adaptation adaptation0 = new Adaptation();
      enactment0.setAdaptation(adaptation0);
      Adaptation adaptation1 = enactment0.getAdaptation();
      assertNull(adaptation1.getName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Date date0 = enactment0.getEnactment_request_time();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      MockDate mockDate0 = new MockDate();
      enactment0.setEnactment_request_time(mockDate0);
      Date date0 = enactment0.getEnactment_request_time();
      assertSame(date0, mockDate0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      String string0 = enactment0.getFc_id();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Adaptation adaptation0 = new Adaptation();
      adaptation0.setRank((-390.33313655013677));
      enactment0.setAdaptation(adaptation0);
      Adaptation adaptation1 = enactment0.getAdaptation();
      assertNull(adaptation1.getModel_system());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      Adaptation adaptation0 = new Adaptation();
      adaptation0.setRank(2308L);
      enactment0.setAdaptation(adaptation0);
      Adaptation adaptation1 = enactment0.getAdaptation();
      assertNull(adaptation1.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      MockDate mockDate0 = new MockDate(0, 1, 0, 1, 1, 1);
      enactment0.setEnactment_completion_time(mockDate0);
      Date date0 = enactment0.getEnactment_completion_time();
      assertSame(date0, mockDate0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      enactment0.setFc_id("");
      String string0 = enactment0.getFc_id();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Enactment enactment0 = new Enactment();
      enactment0.setFc_id("lLv*5ww");
      String string0 = enactment0.getFc_id();
      assertEquals("lLv*5ww", string0);
  }
}
