/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:10:18 GMT 2019
 */

package eu.supersede.integration.api.datastore.fe.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.datastore.fe.types.Label;

public class Label_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Label label0 = new Label();
      label0.setLabel("");
      String string0 = label0.getLabel();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Label label0 = new Label();
      String string0 = label0.getLabel();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Label label0 = new Label();
      int int0 = label0.getProfile_label_id();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Label label0 = new Label();
      String string0 = label0.getLang();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Label label0 = new Label();
      label0.setLabel("eu.supersede.integration.api.datastore.fe.types.Label");
      String string0 = label0.getLabel();
      assertEquals("eu.supersede.integration.api.datastore.fe.types.Label", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Label label0 = new Label();
      label0.setLang("");
      String string0 = label0.getLang();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Label label0 = new Label();
      label0.setLang("G'_");
      String string0 = label0.getLang();
      assertEquals("G'_", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Label label0 = new Label();
      label0.setProfile_label_id((-1822));
      int int0 = label0.getProfile_label_id();
      assertEquals((-1822), int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Label label0 = new Label();
      label0.setProfile_label_id(1144);
      int int0 = label0.getProfile_label_id();
      assertEquals(1144, int0);
  }
}
