/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 23 11:15:30 GMT 2019
 */

package eu.supersede.integration.api.security.test;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import eu.supersede.integration.api.security.test.IFAuthenticationManagerTest;

public class IFAuthenticationManagerTest_ESTest {

  @Test(timeout = 4000)
  @Ignore
  public void test0()  throws Throwable  {
      IFAuthenticationManagerTest iFAuthenticationManagerTest0 = new IFAuthenticationManagerTest();
  }

  @Test(timeout = 4000)
  @Ignore
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        IFAuthenticationManagerTest.setup();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class eu.supersede.integration.api.security.IFAuthenticationManager
         //
      }
  }
}
