/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:41:39 GMT 2019
 */

package eu.supersede.integration.api.replan.optimizer.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.optimizer.types.Priority;

public class Priority_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = priority0.getLevel();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = priority0.getScore();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer(0);
      priority0.setScore(integer0);
      Integer integer1 = priority0.getScore();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer((-1540));
      priority0.setLevel(integer0);
      Integer integer1 = priority0.getLevel();
      assertEquals((-1540), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer(3637);
      priority0.setLevel(integer0);
      Integer integer1 = priority0.getLevel();
      assertEquals(3637, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer(0);
      priority0.setLevel(integer0);
      Integer integer1 = priority0.getLevel();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer((-146));
      priority0.setScore(integer0);
      Integer integer1 = priority0.getScore();
      assertEquals((-146), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Priority priority0 = new Priority();
      Integer integer0 = new Integer(3637);
      priority0.setScore(integer0);
      Integer integer1 = priority0.getScore();
      assertEquals(3637, (int)integer1);
  }
}
