/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:42:59 GMT 2019
 */

package eu.supersede.integration.api.replan.optimizer.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.optimizer.types.Skill;

public class Skill_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Skill skill0 = new Skill();
      skill0.setName("com.fasterxml.jackson.annotation.JsonInclude$Include");
      String string0 = skill0.getName();
      assertEquals("com.fasterxml.jackson.annotation.JsonInclude$Include", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Skill skill0 = new Skill();
      String string0 = skill0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Skill skill0 = new Skill();
      skill0.setName("");
      String string0 = skill0.getName();
      assertEquals("", string0);
  }
}
