/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:20:02 GMT 2019
 */

package eu.supersede.integration.api.feedback.orchestrator.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.orchestrator.types.ApiUser;
import eu.supersede.integration.api.feedback.orchestrator.types.ApiUserApiUserRole;
import eu.supersede.integration.api.feedback.orchestrator.types.ApiUserRole;

public class ApiUserApiUserRole_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole();
      ApiUserRole apiUserRole0 = ApiUserRole.ADMIN;
      apiUserApiUserRole0.setApiUserRole(apiUserRole0);
      assertEquals(ApiUserRole.ADMIN, apiUserApiUserRole0.getApiUserRole());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ApiUser apiUser0 = new ApiUser("9Q8Lup8sFW/T~VM=S", "9Q8Lup8sFW/T~VM=S");
      ApiUserRole apiUserRole0 = ApiUserRole.SUPER_ADMIN;
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole(apiUser0, apiUserRole0);
      ApiUserRole apiUserRole1 = apiUserApiUserRole0.getApiUserRole();
      assertSame(apiUserRole1, apiUserRole0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole();
      long long0 = apiUserApiUserRole0.getId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ApiUserRole apiUserRole0 = ApiUserRole.ADMIN;
      ApiUserApiUserRole apiUserApiUserRole0 = null;
      try {
        apiUserApiUserRole0 = new ApiUserApiUserRole((ApiUser) null, apiUserRole0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole();
      apiUserApiUserRole0.getApiUserRole();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole();
      apiUserApiUserRole0.setId((-93L));
      long long0 = apiUserApiUserRole0.getId();
      assertEquals((-93L), long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ApiUserApiUserRole apiUserApiUserRole0 = new ApiUserApiUserRole();
      apiUserApiUserRole0.setId(1747L);
      long long0 = apiUserApiUserRole0.getId();
      assertEquals(1747L, long0);
  }
}
