/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:21:32 GMT 2019
 */

package eu.supersede.integration.api.feedback.orchestrator.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.orchestrator.types.ApiUserRole;

public class ApiUserRole_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ApiUserRole apiUserRole0 = ApiUserRole.ADMIN;
      String string0 = apiUserRole0.getAuthority();
      assertEquals("ADMIN", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ApiUserRole apiUserRole0 = ApiUserRole.valueOf("SUPER_ADMIN");
      assertEquals(ApiUserRole.SUPER_ADMIN, apiUserRole0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ApiUserRole[] apiUserRoleArray0 = ApiUserRole.values();
      assertEquals(2, apiUserRoleArray0.length);
  }
}
