/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:30:03 GMT 2019
 */

package eu.supersede.integration.api.feedback.orchestrator.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.orchestrator.types.Message;

public class Message_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Message message0 = new Message("!");
      message0.setText("oeD2*Z`h4");
      assertEquals("oeD2*Z`h4", message0.getText());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Message message0 = new Message();
      String string0 = message0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Message message0 = new Message("");
      String string0 = message0.getText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Message message0 = new Message();
      message0.text = "k.o1.!4/";
      String string0 = message0.getText();
      assertEquals("k.o1.!4/", string0);
  }
}
