/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 10:33:48 GMT 2019
 */

package eu.supersede.integration.api.feedback.orchestrator.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.feedback.orchestrator.types.MonitorTool;
import eu.supersede.integration.api.feedback.orchestrator.types.MonitorType;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

public class MonitorType_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      long long0 = monitorType0.getId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      String string0 = monitorType0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      List<MonitorTool> list0 = monitorType0.getMonitorTools();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType((String) null);
      monitorType0.setId((-2401L));
      long long0 = monitorType0.getId();
      assertEquals((-2401L), long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      monitorType0.setId(9223372036854775807L);
      long long0 = monitorType0.getId();
      assertEquals(9223372036854775807L, long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      ArrayList<MonitorTool> arrayList0 = new ArrayList<MonitorTool>();
      monitorType0.setMonitorTools(arrayList0);
      MonitorTool monitorTool0 = new MonitorTool();
      arrayList0.add(monitorTool0);
      List<MonitorTool> list0 = monitorType0.getMonitorTools();
      assertTrue(list0.contains(monitorTool0));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType((String) null);
      Vector<MonitorTool> vector0 = new Vector<MonitorTool>();
      monitorType0.setMonitorTools(vector0);
      List<MonitorTool> list0 = monitorType0.getMonitorTools();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      monitorType0.setName("");
      String string0 = monitorType0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MonitorType monitorType0 = new MonitorType();
      monitorType0.setName("Functions.forPredicate(");
      String string0 = monitorType0.getName();
      assertEquals("Functions.forPredicate(", string0);
  }
}
