/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 09:58:15 GMT 2019
 */

package eu.supersede.integration.api.adaptation.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.adaptation.types.FeatureModel;

public class FeatureModel_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FeatureModel featureModel0 = new FeatureModel();
      assertNull(featureModel0.getAuthorId());
  }
}
