/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:30:27 GMT 2019
 */

package eu.supersede.integration.api.replan.controller.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.controller.types.Priority;

public class Priority_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Priority priority0 = Priority.FOUR;
      Integer integer0 = priority0.getValue();
      assertEquals(4, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Priority priority0 = Priority.TWO;
      String string0 = priority0.toString();
      assertEquals("2", string0);
  }
}
