/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:33:18 GMT 2019
 */

package eu.supersede.integration.api.replan.controller.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.controller.types.FeatureWP3;
import eu.supersede.integration.api.replan.controller.types.Project;
import eu.supersede.integration.api.replan.controller.types.Resource;
import eu.supersede.integration.api.replan.controller.types.Skill;

public class ReplanBaseObject_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Project project0 = new Project();
      String string0 = project0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FeatureWP3 featureWP3_0 = new FeatureWP3();
      featureWP3_0.setDescription("N:VNFmhhzea_V~w3b");
      String string0 = featureWP3_0.getDescription();
      assertEquals("N:VNFmhhzea_V~w3b", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FeatureWP3 featureWP3_0 = new FeatureWP3();
      String string0 = featureWP3_0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Project project0 = new Project();
      project0.setName("com.google.common.reflect.TypeToken$TypeFilter");
      String string0 = project0.getName();
      assertEquals("com.google.common.reflect.TypeToken$TypeFilter", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Skill skill0 = new Skill();
      skill0.setDescription("");
      String string0 = skill0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Resource resource0 = new Resource();
      resource0.setName("");
      String string0 = resource0.getName();
      assertEquals("", string0);
  }
}
