/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:35:16 GMT 2019
 */

package eu.supersede.integration.api.replan.controller.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.controller.types.SoftDependency;
import eu.supersede.integration.api.replan.controller.types.SoftDependencyType;

public class SoftDependency_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      softDependency0.getType();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      Double double0 = softDependency0.getValue();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      SoftDependencyType softDependencyType0 = SoftDependencyType.FUNCTIONAL;
      softDependency0.setType(softDependencyType0);
      assertNull(softDependency0.getValue());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      SoftDependencyType softDependencyType0 = SoftDependencyType.VALUE;
      softDependency0.type = softDependencyType0;
      SoftDependencyType softDependencyType1 = softDependency0.getType();
      assertSame(softDependencyType1, softDependencyType0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      Double double0 = new Double((-242.783));
      softDependency0.setValue(double0);
      Double double1 = softDependency0.getValue();
      assertEquals((-242.783), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      Double double0 = new Double(1897.29);
      softDependency0.setValue(double0);
      Double double1 = softDependency0.getValue();
      assertEquals(1897.29, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SoftDependency softDependency0 = new SoftDependency();
      Double double0 = new Double(0.0);
      softDependency0.setValue(double0);
      Double double1 = softDependency0.getValue();
      assertEquals(0.0, (double)double1, 0.01);
  }
}
