/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:04:30 GMT 2019
 */

package eu.supersede.integration.api.mdm.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.mdm.types.Condition;

public class Condition_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Condition condition0 = new Condition();
      String string0 = condition0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setOperator("");
      String string0 = condition0.getOperator();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Condition condition0 = new Condition();
      String string0 = condition0.getPredicate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Condition condition0 = new Condition();
      String string0 = condition0.getAttribute();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Condition condition0 = new Condition();
      String string0 = condition0.getOperator();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setAttribute("");
      String string0 = condition0.getAttribute();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setAttribute("KS*d2]g%12z.vTgu");
      String string0 = condition0.getAttribute();
      assertEquals("KS*d2]g%12z.vTgu", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setOperator("Y@qqTI6]5!ACkA3ld");
      String string0 = condition0.getOperator();
      assertEquals("Y@qqTI6]5!ACkA3ld", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setPredicate("");
      String string0 = condition0.getPredicate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setPredicate("ERJ^T3Pl7K0e^");
      String string0 = condition0.getPredicate();
      assertEquals("ERJ^T3Pl7K0e^", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setValue("");
      String string0 = condition0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Condition condition0 = new Condition();
      condition0.setValue("D");
      String string0 = condition0.getValue();
      assertEquals("D", string0);
  }
}
