/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:10:04 GMT 2019
 */

package eu.supersede.integration.api.mdm.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.mdm.types.PredicatesTypes;

public class PredicatesTypes_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PredicatesTypes predicatesTypes0 = PredicatesTypes.LT;
      String string0 = predicatesTypes0.val();
      assertEquals("<", string0);
  }
}
