/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:13:49 GMT 2019
 */

package eu.supersede.integration.api.monitoring.manager.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.monitoring.manager.types.MonitorSpecificConfiguration;
import eu.supersede.integration.api.monitoring.manager.types.QoSMonitorConfiguration;

public class MonitorConfiguration_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QoSMonitorConfiguration qoSMonitorConfiguration0 = new QoSMonitorConfiguration();
      MonitorSpecificConfiguration monitorSpecificConfiguration0 = new MonitorSpecificConfiguration();
      qoSMonitorConfiguration0.setMonitorSpecificConfiguration(monitorSpecificConfiguration0);
      MonitorSpecificConfiguration monitorSpecificConfiguration1 = qoSMonitorConfiguration0.getMonitorSpecificConfiguration();
      assertSame(monitorSpecificConfiguration1, monitorSpecificConfiguration0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QoSMonitorConfiguration qoSMonitorConfiguration0 = new QoSMonitorConfiguration();
      MonitorSpecificConfiguration monitorSpecificConfiguration0 = qoSMonitorConfiguration0.getMonitorSpecificConfiguration();
      assertNull(monitorSpecificConfiguration0);
  }
}
