/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:15:44 GMT 2019
 */

package eu.supersede.integration.api.monitoring.manager.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.monitoring.manager.types.QoSMonitorConfiguration;

public class QoSMonitorConfiguration_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QoSMonitorConfiguration qoSMonitorConfiguration0 = new QoSMonitorConfiguration();
  }
}
