/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:15:54 GMT 2019
 */

package eu.supersede.integration.api.monitoring.manager.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.monitoring.manager.types.SocialNetworkMonitorConfiguration;

public class SocialNetworkMonitorConfiguration_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SocialNetworkMonitorConfiguration socialNetworkMonitorConfiguration0 = new SocialNetworkMonitorConfiguration();
  }
}
