/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:17:05 GMT 2019
 */

package eu.supersede.integration.api.monitoring.manager.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.monitoring.manager.types.TwitterMonitorConfiguration;
import java.util.ArrayList;
import java.util.List;

public class TwitterMonitorConfiguration_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TwitterMonitorConfiguration twitterMonitorConfiguration0 = new TwitterMonitorConfiguration();
      String string0 = twitterMonitorConfiguration0.getKeywordExpression();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TwitterMonitorConfiguration twitterMonitorConfiguration0 = new TwitterMonitorConfiguration();
      List<String> list0 = twitterMonitorConfiguration0.getAccounts();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TwitterMonitorConfiguration twitterMonitorConfiguration0 = new TwitterMonitorConfiguration();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add((String) null);
      twitterMonitorConfiguration0.setAccounts(arrayList0);
      List<String> list0 = twitterMonitorConfiguration0.getAccounts();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TwitterMonitorConfiguration twitterMonitorConfiguration0 = new TwitterMonitorConfiguration();
      twitterMonitorConfiguration0.setKeywordExpression("");
      String string0 = twitterMonitorConfiguration0.getKeywordExpression();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TwitterMonitorConfiguration twitterMonitorConfiguration0 = new TwitterMonitorConfiguration();
      twitterMonitorConfiguration0.setKeywordExpression("com.google.common.cache.ForwardingCache");
      String string0 = twitterMonitorConfiguration0.getKeywordExpression();
      assertEquals("com.google.common.cache.ForwardingCache", string0);
  }
}
