/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:43:10 GMT 2019
 */

package eu.supersede.integration.api.replan.optimizer_v2.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.optimizer_v2.types.AlgorithmParameters;
import eu.supersede.integration.api.replan.optimizer_v2.types.AlgorithmType;

public class AlgorithmParameters_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer(4);
      algorithmParameters0.setNumberOfIterations(integer0);
      Integer integer1 = algorithmParameters0.getNumberOfIterations();
      assertEquals(4, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = algorithmParameters0.getCrossoverProbability();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer(4);
      algorithmParameters0.setPopulationSize(integer0);
      Integer integer1 = algorithmParameters0.getPopulationSize();
      assertEquals(4, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      algorithmParameters0.getAlgorithmType();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = algorithmParameters0.getRateOfNotRandomSolution();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = algorithmParameters0.getNumberOfIterations();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = algorithmParameters0.getPopulationSize();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      AlgorithmType algorithmType0 = AlgorithmType.SPEA2;
      algorithmParameters0.setAlgorithmType(algorithmType0);
      AlgorithmType algorithmType1 = algorithmParameters0.getAlgorithmType();
      assertEquals(AlgorithmType.SPEA2, algorithmType1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double((-2570.98841767));
      algorithmParameters0.setCrossoverProbability(double0);
      Double double1 = algorithmParameters0.getCrossoverProbability();
      assertEquals((-2570.98841767), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double(1.0);
      algorithmParameters0.setCrossoverProbability(double0);
      Double double1 = algorithmParameters0.getCrossoverProbability();
      assertEquals(1.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double(0.0);
      algorithmParameters0.setCrossoverProbability(double0);
      Double double1 = algorithmParameters0.getCrossoverProbability();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer((-1363376845));
      algorithmParameters0.setNumberOfIterations(integer0);
      Integer integer1 = algorithmParameters0.getNumberOfIterations();
      assertEquals((-1363376845), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer(0);
      algorithmParameters0.setNumberOfIterations(integer0);
      Integer integer1 = algorithmParameters0.getNumberOfIterations();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer((-1));
      algorithmParameters0.setPopulationSize(integer0);
      Integer integer1 = algorithmParameters0.getPopulationSize();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Integer integer0 = new Integer(0);
      algorithmParameters0.setPopulationSize(integer0);
      Integer integer1 = algorithmParameters0.getPopulationSize();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double((-339.6));
      algorithmParameters0.setRateOfNotRandomSolution(double0);
      Double double1 = algorithmParameters0.getRateOfNotRandomSolution();
      assertEquals((-339.6), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double(2326.87);
      algorithmParameters0.setRateOfNotRandomSolution(double0);
      Double double1 = algorithmParameters0.getRateOfNotRandomSolution();
      assertEquals(2326.87, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AlgorithmParameters algorithmParameters0 = new AlgorithmParameters();
      Double double0 = new Double(0.0);
      algorithmParameters0.setRateOfNotRandomSolution(double0);
      Double double1 = algorithmParameters0.getRateOfNotRandomSolution();
      assertEquals(0.0, (double)double1, 0.01);
  }
}
