/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:49:38 GMT 2019
 */

package eu.supersede.integration.api.replan.optimizer_v2.types;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.supersede.integration.api.replan.optimizer_v2.types.Skill;

public class Skill_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Skill skill0 = new Skill();
      skill0.setName("");
      String string0 = skill0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Skill skill0 = new Skill();
      String string0 = skill0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Skill skill0 = new Skill();
      skill0.setName("GSQ$<n&D^f@dP!");
      String string0 = skill0.getName();
      assertNotNull(string0);
  }
}
